//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebservice.ModulaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ModulaService.IModulaPR")]
    public interface IModulaPR {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModulaPR/GetItem", ReplyAction="http://tempuri.org/IModulaPR/GetItemResponse")]
        SyncServices.ItemEntity GetItem(string itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModulaPR/GetItems", ReplyAction="http://tempuri.org/IModulaPR/GetItemsResponse")]
        SyncServices.ItemEntity[] GetItems(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModulaPR/GetWOPools", ReplyAction="http://tempuri.org/IModulaPR/GetWOPoolsResponse")]
        SyncServices.WOPool[] GetWOPools();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModulaPR/GetEquipments", ReplyAction="http://tempuri.org/IModulaPR/GetEquipmentsResponse")]
        SyncServices.PMEquipment[] GetEquipments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModulaPR/GetFailureCodes", ReplyAction="http://tempuri.org/IModulaPR/GetFailureCodesResponse")]
        SyncServices.PMFailureCode[] GetFailureCodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModulaPR/GetRepairCodes", ReplyAction="http://tempuri.org/IModulaPR/GetRepairCodesResponse")]
        SyncServices.PMRepairCode[] GetRepairCodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModulaPR/GetEquipment", ReplyAction="http://tempuri.org/IModulaPR/GetEquipmentResponse")]
        SyncServices.PMEquipment GetEquipment(string equipId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModulaPR/GetWorkOrderTypes", ReplyAction="http://tempuri.org/IModulaPR/GetWorkOrderTypesResponse")]
        SyncServices.EAMServices.WOTypeContract[] GetWorkOrderTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModulaPR/GetEquipLocations", ReplyAction="http://tempuri.org/IModulaPR/GetEquipLocationsResponse")]
        SyncServices.EAMServices.WOLocationContract[] GetEquipLocations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModulaPR/GetInlineWorkItems", ReplyAction="http://tempuri.org/IModulaPR/GetInlineWorkItemsResponse")]
        SyncServices.PMWorkItem[] GetInlineWorkItems(string workOrderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModulaPR/GetOtherWorkItems", ReplyAction="http://tempuri.org/IModulaPR/GetOtherWorkItemsResponse")]
        SyncServices.PMWorkItem[] GetOtherWorkItems(string workOrderId, string search, int topRecords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModulaPR/SaveWorkOrder", ReplyAction="http://tempuri.org/IModulaPR/SaveWorkOrderResponse")]
        SyncServices.PMWorkOrder SaveWorkOrder(SyncServices.PMWorkOrder entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModulaPR/SetWorkOrderStatus", ReplyAction="http://tempuri.org/IModulaPR/SetWorkOrderStatusResponse")]
        int SetWorkOrderStatus(string workOrderId, int statusId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModulaPR/DeleteWorkItem", ReplyAction="http://tempuri.org/IModulaPR/DeleteWorkItemResponse")]
        int DeleteWorkItem(string workOrderId, int sto_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModulaPR/GetPing", ReplyAction="http://tempuri.org/IModulaPR/GetPingResponse")]
        string GetPing();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModulaPRChannel : TestWebservice.ModulaService.IModulaPR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModulaPRClient : System.ServiceModel.ClientBase<TestWebservice.ModulaService.IModulaPR>, TestWebservice.ModulaService.IModulaPR {
        
        public ModulaPRClient() {
        }
        
        public ModulaPRClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModulaPRClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModulaPRClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModulaPRClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SyncServices.ItemEntity GetItem(string itemId) {
            return base.Channel.GetItem(itemId);
        }
        
        public SyncServices.ItemEntity[] GetItems(string search) {
            return base.Channel.GetItems(search);
        }
        
        public SyncServices.WOPool[] GetWOPools() {
            return base.Channel.GetWOPools();
        }
        
        public SyncServices.PMEquipment[] GetEquipments() {
            return base.Channel.GetEquipments();
        }
        
        public SyncServices.PMFailureCode[] GetFailureCodes() {
            return base.Channel.GetFailureCodes();
        }
        
        public SyncServices.PMRepairCode[] GetRepairCodes() {
            return base.Channel.GetRepairCodes();
        }
        
        public SyncServices.PMEquipment GetEquipment(string equipId) {
            return base.Channel.GetEquipment(equipId);
        }
        
        public SyncServices.EAMServices.WOTypeContract[] GetWorkOrderTypes() {
            return base.Channel.GetWorkOrderTypes();
        }
        
        public SyncServices.EAMServices.WOLocationContract[] GetEquipLocations() {
            return base.Channel.GetEquipLocations();
        }
        
        public SyncServices.PMWorkItem[] GetInlineWorkItems(string workOrderId) {
            return base.Channel.GetInlineWorkItems(workOrderId);
        }
        
        public SyncServices.PMWorkItem[] GetOtherWorkItems(string workOrderId, string search, int topRecords) {
            return base.Channel.GetOtherWorkItems(workOrderId, search, topRecords);
        }
        
        public SyncServices.PMWorkOrder SaveWorkOrder(SyncServices.PMWorkOrder entity) {
            return base.Channel.SaveWorkOrder(entity);
        }
        
        public int SetWorkOrderStatus(string workOrderId, int statusId) {
            return base.Channel.SetWorkOrderStatus(workOrderId, statusId);
        }
        
        public int DeleteWorkItem(string workOrderId, int sto_id) {
            return base.Channel.DeleteWorkItem(workOrderId, sto_id);
        }
        
        public string GetPing() {
            return base.Channel.GetPing();
        }
    }
}
