//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebservice.SalesOrderService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestWebservice.SalesOrderService.SalesLineContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestWebservice.SalesOrderService.InventByGrLocContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestWebservice.SalesOrderService.SalesTableContract))]
    public partial class XppObjectBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.ComponentModel.PropertyChangedEventHandler PropertyChanged1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="PropertyChanged", IsRequired=true)]
        public System.ComponentModel.PropertyChangedEventHandler PropertyChanged1 {
            get {
                return this.PropertyChanged1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyChanged1Field, value) != true)) {
                    this.PropertyChanged1Field = value;
                    this.RaisePropertyChanged("PropertyChanged1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesLineContract", Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
    [System.SerializableAttribute()]
    public partial class SalesLineContract : TestWebservice.SalesOrderService.XppObjectBase {
        
        private bool exclusiveHalfPalletFieldField;
        
        private bool exclusiveHalfPalletFieldSpecifiedField;
        
        private string gradeFieldField;
        
        private string inventTransIDFieldField;
        
        private bool isHalfPalletFieldField;
        
        private bool isHalfPalletFieldSpecifiedField;
        
        private string itemIdFieldField;
        
        private long lineRecIdFieldField;
        
        private bool lineRecIdFieldSpecifiedField;
        
        private TestWebservice.SalesOrderService.InventByGrLocContract[] locationsFieldField;
        
        private string nameFieldField;
        
        private string pickingIdFieldField;
        
        private string remarksFieldField;
        
        private string salesIdFieldField;
        
        private decimal salesQtyBoxFieldField;
        
        private bool salesQtyBoxFieldSpecifiedField;
        
        private decimal salesQtyFieldField;
        
        private bool salesQtyFieldSpecifiedField;
        
        private decimal salesQtyPalletFieldField;
        
        private bool salesQtyPalletFieldSpecifiedField;
        
        private decimal salesQtySQMFieldField;
        
        private bool salesQtySQMFieldSpecifiedField;
        
        private decimal salesQtySQMRemainingFieldField;
        
        private bool salesQtySQMRemainingFieldSpecifiedField;
        
        private decimal salesQtySQMReservedFieldField;
        
        private bool salesQtySQMReservedFieldSpecifiedField;
        
        private string salesUnitFieldField;
        
        private string serialFieldField;
        
        private string shadeFieldField;
        
        private string siteFieldField;
        
        private string sizeFieldField;
        
        private TestWebservice.SalesOrderService.PalletStatus updateStatusFieldField;
        
        private bool updateStatusFieldSpecifiedField;
        
        private string updatedByFieldField;
        
        private System.DateTime updatedDateFieldField;
        
        private bool updatedDateFieldSpecifiedField;
        
        private string wLocationIdFieldField;
        
        private string warehouseFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool exclusiveHalfPalletField {
            get {
                return this.exclusiveHalfPalletFieldField;
            }
            set {
                if ((this.exclusiveHalfPalletFieldField.Equals(value) != true)) {
                    this.exclusiveHalfPalletFieldField = value;
                    this.RaisePropertyChanged("exclusiveHalfPalletField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool exclusiveHalfPalletFieldSpecified {
            get {
                return this.exclusiveHalfPalletFieldSpecifiedField;
            }
            set {
                if ((this.exclusiveHalfPalletFieldSpecifiedField.Equals(value) != true)) {
                    this.exclusiveHalfPalletFieldSpecifiedField = value;
                    this.RaisePropertyChanged("exclusiveHalfPalletFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string gradeField {
            get {
                return this.gradeFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.gradeFieldField, value) != true)) {
                    this.gradeFieldField = value;
                    this.RaisePropertyChanged("gradeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string inventTransIDField {
            get {
                return this.inventTransIDFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.inventTransIDFieldField, value) != true)) {
                    this.inventTransIDFieldField = value;
                    this.RaisePropertyChanged("inventTransIDField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool isHalfPalletField {
            get {
                return this.isHalfPalletFieldField;
            }
            set {
                if ((this.isHalfPalletFieldField.Equals(value) != true)) {
                    this.isHalfPalletFieldField = value;
                    this.RaisePropertyChanged("isHalfPalletField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool isHalfPalletFieldSpecified {
            get {
                return this.isHalfPalletFieldSpecifiedField;
            }
            set {
                if ((this.isHalfPalletFieldSpecifiedField.Equals(value) != true)) {
                    this.isHalfPalletFieldSpecifiedField = value;
                    this.RaisePropertyChanged("isHalfPalletFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string itemIdField {
            get {
                return this.itemIdFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.itemIdFieldField, value) != true)) {
                    this.itemIdFieldField = value;
                    this.RaisePropertyChanged("itemIdField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long lineRecIdField {
            get {
                return this.lineRecIdFieldField;
            }
            set {
                if ((this.lineRecIdFieldField.Equals(value) != true)) {
                    this.lineRecIdFieldField = value;
                    this.RaisePropertyChanged("lineRecIdField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool lineRecIdFieldSpecified {
            get {
                return this.lineRecIdFieldSpecifiedField;
            }
            set {
                if ((this.lineRecIdFieldSpecifiedField.Equals(value) != true)) {
                    this.lineRecIdFieldSpecifiedField = value;
                    this.RaisePropertyChanged("lineRecIdFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TestWebservice.SalesOrderService.InventByGrLocContract[] locationsField {
            get {
                return this.locationsFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.locationsFieldField, value) != true)) {
                    this.locationsFieldField = value;
                    this.RaisePropertyChanged("locationsField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nameField {
            get {
                return this.nameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.nameFieldField, value) != true)) {
                    this.nameFieldField = value;
                    this.RaisePropertyChanged("nameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string pickingIdField {
            get {
                return this.pickingIdFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pickingIdFieldField, value) != true)) {
                    this.pickingIdFieldField = value;
                    this.RaisePropertyChanged("pickingIdField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string remarksField {
            get {
                return this.remarksFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.remarksFieldField, value) != true)) {
                    this.remarksFieldField = value;
                    this.RaisePropertyChanged("remarksField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string salesIdField {
            get {
                return this.salesIdFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.salesIdFieldField, value) != true)) {
                    this.salesIdFieldField = value;
                    this.RaisePropertyChanged("salesIdField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal salesQtyBoxField {
            get {
                return this.salesQtyBoxFieldField;
            }
            set {
                if ((this.salesQtyBoxFieldField.Equals(value) != true)) {
                    this.salesQtyBoxFieldField = value;
                    this.RaisePropertyChanged("salesQtyBoxField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool salesQtyBoxFieldSpecified {
            get {
                return this.salesQtyBoxFieldSpecifiedField;
            }
            set {
                if ((this.salesQtyBoxFieldSpecifiedField.Equals(value) != true)) {
                    this.salesQtyBoxFieldSpecifiedField = value;
                    this.RaisePropertyChanged("salesQtyBoxFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal salesQtyField {
            get {
                return this.salesQtyFieldField;
            }
            set {
                if ((this.salesQtyFieldField.Equals(value) != true)) {
                    this.salesQtyFieldField = value;
                    this.RaisePropertyChanged("salesQtyField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool salesQtyFieldSpecified {
            get {
                return this.salesQtyFieldSpecifiedField;
            }
            set {
                if ((this.salesQtyFieldSpecifiedField.Equals(value) != true)) {
                    this.salesQtyFieldSpecifiedField = value;
                    this.RaisePropertyChanged("salesQtyFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal salesQtyPalletField {
            get {
                return this.salesQtyPalletFieldField;
            }
            set {
                if ((this.salesQtyPalletFieldField.Equals(value) != true)) {
                    this.salesQtyPalletFieldField = value;
                    this.RaisePropertyChanged("salesQtyPalletField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool salesQtyPalletFieldSpecified {
            get {
                return this.salesQtyPalletFieldSpecifiedField;
            }
            set {
                if ((this.salesQtyPalletFieldSpecifiedField.Equals(value) != true)) {
                    this.salesQtyPalletFieldSpecifiedField = value;
                    this.RaisePropertyChanged("salesQtyPalletFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal salesQtySQMField {
            get {
                return this.salesQtySQMFieldField;
            }
            set {
                if ((this.salesQtySQMFieldField.Equals(value) != true)) {
                    this.salesQtySQMFieldField = value;
                    this.RaisePropertyChanged("salesQtySQMField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool salesQtySQMFieldSpecified {
            get {
                return this.salesQtySQMFieldSpecifiedField;
            }
            set {
                if ((this.salesQtySQMFieldSpecifiedField.Equals(value) != true)) {
                    this.salesQtySQMFieldSpecifiedField = value;
                    this.RaisePropertyChanged("salesQtySQMFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal salesQtySQMRemainingField {
            get {
                return this.salesQtySQMRemainingFieldField;
            }
            set {
                if ((this.salesQtySQMRemainingFieldField.Equals(value) != true)) {
                    this.salesQtySQMRemainingFieldField = value;
                    this.RaisePropertyChanged("salesQtySQMRemainingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool salesQtySQMRemainingFieldSpecified {
            get {
                return this.salesQtySQMRemainingFieldSpecifiedField;
            }
            set {
                if ((this.salesQtySQMRemainingFieldSpecifiedField.Equals(value) != true)) {
                    this.salesQtySQMRemainingFieldSpecifiedField = value;
                    this.RaisePropertyChanged("salesQtySQMRemainingFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal salesQtySQMReservedField {
            get {
                return this.salesQtySQMReservedFieldField;
            }
            set {
                if ((this.salesQtySQMReservedFieldField.Equals(value) != true)) {
                    this.salesQtySQMReservedFieldField = value;
                    this.RaisePropertyChanged("salesQtySQMReservedField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool salesQtySQMReservedFieldSpecified {
            get {
                return this.salesQtySQMReservedFieldSpecifiedField;
            }
            set {
                if ((this.salesQtySQMReservedFieldSpecifiedField.Equals(value) != true)) {
                    this.salesQtySQMReservedFieldSpecifiedField = value;
                    this.RaisePropertyChanged("salesQtySQMReservedFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string salesUnitField {
            get {
                return this.salesUnitFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.salesUnitFieldField, value) != true)) {
                    this.salesUnitFieldField = value;
                    this.RaisePropertyChanged("salesUnitField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string serialField {
            get {
                return this.serialFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.serialFieldField, value) != true)) {
                    this.serialFieldField = value;
                    this.RaisePropertyChanged("serialField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string shadeField {
            get {
                return this.shadeFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.shadeFieldField, value) != true)) {
                    this.shadeFieldField = value;
                    this.RaisePropertyChanged("shadeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string siteField {
            get {
                return this.siteFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.siteFieldField, value) != true)) {
                    this.siteFieldField = value;
                    this.RaisePropertyChanged("siteField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string sizeField {
            get {
                return this.sizeFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.sizeFieldField, value) != true)) {
                    this.sizeFieldField = value;
                    this.RaisePropertyChanged("sizeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TestWebservice.SalesOrderService.PalletStatus updateStatusField {
            get {
                return this.updateStatusFieldField;
            }
            set {
                if ((this.updateStatusFieldField.Equals(value) != true)) {
                    this.updateStatusFieldField = value;
                    this.RaisePropertyChanged("updateStatusField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool updateStatusFieldSpecified {
            get {
                return this.updateStatusFieldSpecifiedField;
            }
            set {
                if ((this.updateStatusFieldSpecifiedField.Equals(value) != true)) {
                    this.updateStatusFieldSpecifiedField = value;
                    this.RaisePropertyChanged("updateStatusFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string updatedByField {
            get {
                return this.updatedByFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.updatedByFieldField, value) != true)) {
                    this.updatedByFieldField = value;
                    this.RaisePropertyChanged("updatedByField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime updatedDateField {
            get {
                return this.updatedDateFieldField;
            }
            set {
                if ((this.updatedDateFieldField.Equals(value) != true)) {
                    this.updatedDateFieldField = value;
                    this.RaisePropertyChanged("updatedDateField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool updatedDateFieldSpecified {
            get {
                return this.updatedDateFieldSpecifiedField;
            }
            set {
                if ((this.updatedDateFieldSpecifiedField.Equals(value) != true)) {
                    this.updatedDateFieldSpecifiedField = value;
                    this.RaisePropertyChanged("updatedDateFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string wLocationIdField {
            get {
                return this.wLocationIdFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.wLocationIdFieldField, value) != true)) {
                    this.wLocationIdFieldField = value;
                    this.RaisePropertyChanged("wLocationIdField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string warehouseField {
            get {
                return this.warehouseFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.warehouseFieldField, value) != true)) {
                    this.warehouseFieldField = value;
                    this.RaisePropertyChanged("warehouseField");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InventByGrLocContract", Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
    [System.SerializableAttribute()]
    public partial class InventByGrLocContract : TestWebservice.SalesOrderService.XppObjectBase {
        
        private string gradeFieldField;
        
        private string locationIdFieldField;
        
        private decimal onHandFieldField;
        
        private bool onHandFieldSpecifiedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string gradeField {
            get {
                return this.gradeFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.gradeFieldField, value) != true)) {
                    this.gradeFieldField = value;
                    this.RaisePropertyChanged("gradeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string locationIdField {
            get {
                return this.locationIdFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.locationIdFieldField, value) != true)) {
                    this.locationIdFieldField = value;
                    this.RaisePropertyChanged("locationIdField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal onHandField {
            get {
                return this.onHandFieldField;
            }
            set {
                if ((this.onHandFieldField.Equals(value) != true)) {
                    this.onHandFieldField = value;
                    this.RaisePropertyChanged("onHandField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool onHandFieldSpecified {
            get {
                return this.onHandFieldSpecifiedField;
            }
            set {
                if ((this.onHandFieldSpecifiedField.Equals(value) != true)) {
                    this.onHandFieldSpecifiedField = value;
                    this.RaisePropertyChanged("onHandFieldSpecified");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesTableContract", Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
    [System.SerializableAttribute()]
    public partial class SalesTableContract : TestWebservice.SalesOrderService.XppObjectBase {
        
        private string customerIdFieldField;
        
        private string customerNameFieldField;
        
        private System.DateTime deliveryDateFieldField;
        
        private bool deliveryDateFieldSpecifiedField;
        
        private string deliveryModeFieldField;
        
        private string deliveryNameFieldField;
        
        private string driverNameFieldField;
        
        private TestWebservice.SalesOrderService.NoYes halfPalletFieldField;
        
        private bool halfPalletFieldSpecifiedField;
        
        private string packingSlipFieldField;
        
        private string pickingIdFieldField;
        
        private string salesIdFieldField;
        
        private TestWebservice.SalesOrderService.SalesLineContract[] salesLinesFieldField;
        
        private string salesNameFieldField;
        
        private TestWebservice.SalesOrderService.SalesStatus salesStatusFieldField;
        
        private bool salesStatusFieldSpecifiedField;
        
        private TestWebservice.SalesOrderService.SalesType salesTypeFieldField;
        
        private bool salesTypeFieldSpecifiedField;
        
        private TestWebservice.SalesOrderService.NoYes sameConfigurationFieldField;
        
        private bool sameConfigurationFieldSpecifiedField;
        
        private System.DateTime startLoadFieldField;
        
        private bool startLoadFieldSpecifiedField;
        
        private System.DateTime stopLoadFieldField;
        
        private bool stopLoadFieldSpecifiedField;
        
        private int truckLoadLineFieldField;
        
        private bool truckLoadLineFieldSpecifiedField;
        
        private string truckPlateFieldField;
        
        private string truckTicketFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string customerIdField {
            get {
                return this.customerIdFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.customerIdFieldField, value) != true)) {
                    this.customerIdFieldField = value;
                    this.RaisePropertyChanged("customerIdField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string customerNameField {
            get {
                return this.customerNameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.customerNameFieldField, value) != true)) {
                    this.customerNameFieldField = value;
                    this.RaisePropertyChanged("customerNameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime deliveryDateField {
            get {
                return this.deliveryDateFieldField;
            }
            set {
                if ((this.deliveryDateFieldField.Equals(value) != true)) {
                    this.deliveryDateFieldField = value;
                    this.RaisePropertyChanged("deliveryDateField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool deliveryDateFieldSpecified {
            get {
                return this.deliveryDateFieldSpecifiedField;
            }
            set {
                if ((this.deliveryDateFieldSpecifiedField.Equals(value) != true)) {
                    this.deliveryDateFieldSpecifiedField = value;
                    this.RaisePropertyChanged("deliveryDateFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string deliveryModeField {
            get {
                return this.deliveryModeFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.deliveryModeFieldField, value) != true)) {
                    this.deliveryModeFieldField = value;
                    this.RaisePropertyChanged("deliveryModeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string deliveryNameField {
            get {
                return this.deliveryNameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.deliveryNameFieldField, value) != true)) {
                    this.deliveryNameFieldField = value;
                    this.RaisePropertyChanged("deliveryNameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string driverNameField {
            get {
                return this.driverNameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.driverNameFieldField, value) != true)) {
                    this.driverNameFieldField = value;
                    this.RaisePropertyChanged("driverNameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TestWebservice.SalesOrderService.NoYes halfPalletField {
            get {
                return this.halfPalletFieldField;
            }
            set {
                if ((this.halfPalletFieldField.Equals(value) != true)) {
                    this.halfPalletFieldField = value;
                    this.RaisePropertyChanged("halfPalletField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool halfPalletFieldSpecified {
            get {
                return this.halfPalletFieldSpecifiedField;
            }
            set {
                if ((this.halfPalletFieldSpecifiedField.Equals(value) != true)) {
                    this.halfPalletFieldSpecifiedField = value;
                    this.RaisePropertyChanged("halfPalletFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string packingSlipField {
            get {
                return this.packingSlipFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.packingSlipFieldField, value) != true)) {
                    this.packingSlipFieldField = value;
                    this.RaisePropertyChanged("packingSlipField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string pickingIdField {
            get {
                return this.pickingIdFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pickingIdFieldField, value) != true)) {
                    this.pickingIdFieldField = value;
                    this.RaisePropertyChanged("pickingIdField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string salesIdField {
            get {
                return this.salesIdFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.salesIdFieldField, value) != true)) {
                    this.salesIdFieldField = value;
                    this.RaisePropertyChanged("salesIdField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TestWebservice.SalesOrderService.SalesLineContract[] salesLinesField {
            get {
                return this.salesLinesFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.salesLinesFieldField, value) != true)) {
                    this.salesLinesFieldField = value;
                    this.RaisePropertyChanged("salesLinesField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string salesNameField {
            get {
                return this.salesNameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.salesNameFieldField, value) != true)) {
                    this.salesNameFieldField = value;
                    this.RaisePropertyChanged("salesNameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TestWebservice.SalesOrderService.SalesStatus salesStatusField {
            get {
                return this.salesStatusFieldField;
            }
            set {
                if ((this.salesStatusFieldField.Equals(value) != true)) {
                    this.salesStatusFieldField = value;
                    this.RaisePropertyChanged("salesStatusField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool salesStatusFieldSpecified {
            get {
                return this.salesStatusFieldSpecifiedField;
            }
            set {
                if ((this.salesStatusFieldSpecifiedField.Equals(value) != true)) {
                    this.salesStatusFieldSpecifiedField = value;
                    this.RaisePropertyChanged("salesStatusFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TestWebservice.SalesOrderService.SalesType salesTypeField {
            get {
                return this.salesTypeFieldField;
            }
            set {
                if ((this.salesTypeFieldField.Equals(value) != true)) {
                    this.salesTypeFieldField = value;
                    this.RaisePropertyChanged("salesTypeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool salesTypeFieldSpecified {
            get {
                return this.salesTypeFieldSpecifiedField;
            }
            set {
                if ((this.salesTypeFieldSpecifiedField.Equals(value) != true)) {
                    this.salesTypeFieldSpecifiedField = value;
                    this.RaisePropertyChanged("salesTypeFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TestWebservice.SalesOrderService.NoYes sameConfigurationField {
            get {
                return this.sameConfigurationFieldField;
            }
            set {
                if ((this.sameConfigurationFieldField.Equals(value) != true)) {
                    this.sameConfigurationFieldField = value;
                    this.RaisePropertyChanged("sameConfigurationField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool sameConfigurationFieldSpecified {
            get {
                return this.sameConfigurationFieldSpecifiedField;
            }
            set {
                if ((this.sameConfigurationFieldSpecifiedField.Equals(value) != true)) {
                    this.sameConfigurationFieldSpecifiedField = value;
                    this.RaisePropertyChanged("sameConfigurationFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime startLoadField {
            get {
                return this.startLoadFieldField;
            }
            set {
                if ((this.startLoadFieldField.Equals(value) != true)) {
                    this.startLoadFieldField = value;
                    this.RaisePropertyChanged("startLoadField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool startLoadFieldSpecified {
            get {
                return this.startLoadFieldSpecifiedField;
            }
            set {
                if ((this.startLoadFieldSpecifiedField.Equals(value) != true)) {
                    this.startLoadFieldSpecifiedField = value;
                    this.RaisePropertyChanged("startLoadFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime stopLoadField {
            get {
                return this.stopLoadFieldField;
            }
            set {
                if ((this.stopLoadFieldField.Equals(value) != true)) {
                    this.stopLoadFieldField = value;
                    this.RaisePropertyChanged("stopLoadField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool stopLoadFieldSpecified {
            get {
                return this.stopLoadFieldSpecifiedField;
            }
            set {
                if ((this.stopLoadFieldSpecifiedField.Equals(value) != true)) {
                    this.stopLoadFieldSpecifiedField = value;
                    this.RaisePropertyChanged("stopLoadFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int truckLoadLineField {
            get {
                return this.truckLoadLineFieldField;
            }
            set {
                if ((this.truckLoadLineFieldField.Equals(value) != true)) {
                    this.truckLoadLineFieldField = value;
                    this.RaisePropertyChanged("truckLoadLineField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool truckLoadLineFieldSpecified {
            get {
                return this.truckLoadLineFieldSpecifiedField;
            }
            set {
                if ((this.truckLoadLineFieldSpecifiedField.Equals(value) != true)) {
                    this.truckLoadLineFieldSpecifiedField = value;
                    this.RaisePropertyChanged("truckLoadLineFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string truckPlateField {
            get {
                return this.truckPlateFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.truckPlateFieldField, value) != true)) {
                    this.truckPlateFieldField = value;
                    this.RaisePropertyChanged("truckPlateField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string truckTicketField {
            get {
                return this.truckTicketFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.truckTicketFieldField, value) != true)) {
                    this.truckTicketFieldField = value;
                    this.RaisePropertyChanged("truckTicketField");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoYes", Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
    public enum NoYes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yes = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesStatus", Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
    public enum SalesStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Backorder = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delivered = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoiced = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesType", Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
    public enum SalesType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Journal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DEL_Quotation = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Subscription = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sales = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReturnItem = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DEL_Blanket = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ItemReq = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PalletStatus", Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
    public enum PalletStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Search = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Remove = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reserve = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnReserve = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PickingList = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalesOrderService.ISalesOrderService")]
    public interface ISalesOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesOrderService/FindSalesOrder", ReplyAction="http://tempuri.org/ISalesOrderService/FindSalesOrderResponse")]
        TestWebservice.SalesOrderService.SalesTableContract FindSalesOrder(string salesId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesOrderService/GetPing", ReplyAction="http://tempuri.org/ISalesOrderService/GetPingResponse")]
        string GetPing();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalesOrderServiceChannel : TestWebservice.SalesOrderService.ISalesOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesOrderServiceClient : System.ServiceModel.ClientBase<TestWebservice.SalesOrderService.ISalesOrderService>, TestWebservice.SalesOrderService.ISalesOrderService {
        
        public SalesOrderServiceClient() {
        }
        
        public SalesOrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesOrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesOrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesOrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestWebservice.SalesOrderService.SalesTableContract FindSalesOrder(string salesId) {
            return base.Channel.FindSalesOrder(salesId);
        }
        
        public string GetPing() {
            return base.Channel.GetPing();
        }
    }
}
