//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebservice.SCSyncService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemEntity", Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
    [System.SerializableAttribute()]
    public partial class ItemEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AvailableCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLockedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsManualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMatchedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LockDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PhysicalCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ProcessByITField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SyncIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UoMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AvailableCount {
            get {
                return this.AvailableCountField;
            }
            set {
                if ((this.AvailableCountField.Equals(value) != true)) {
                    this.AvailableCountField = value;
                    this.RaisePropertyChanged("AvailableCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateUpdated {
            get {
                return this.DateUpdatedField;
            }
            set {
                if ((this.DateUpdatedField.Equals(value) != true)) {
                    this.DateUpdatedField = value;
                    this.RaisePropertyChanged("DateUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceName {
            get {
                return this.DeviceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceNameField, value) != true)) {
                    this.DeviceNameField = value;
                    this.RaisePropertyChanged("DeviceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLocked {
            get {
                return this.IsLockedField;
            }
            set {
                if ((this.IsLockedField.Equals(value) != true)) {
                    this.IsLockedField = value;
                    this.RaisePropertyChanged("IsLocked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsManual {
            get {
                return this.IsManualField;
            }
            set {
                if ((this.IsManualField.Equals(value) != true)) {
                    this.IsManualField = value;
                    this.RaisePropertyChanged("IsManual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMatched {
            get {
                return this.IsMatchedField;
            }
            set {
                if ((this.IsMatchedField.Equals(value) != true)) {
                    this.IsMatchedField = value;
                    this.RaisePropertyChanged("IsMatched");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LockDate {
            get {
                return this.LockDateField;
            }
            set {
                if ((this.LockDateField.Equals(value) != true)) {
                    this.LockDateField = value;
                    this.RaisePropertyChanged("LockDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PhysicalCount {
            get {
                return this.PhysicalCountField;
            }
            set {
                if ((this.PhysicalCountField.Equals(value) != true)) {
                    this.PhysicalCountField = value;
                    this.RaisePropertyChanged("PhysicalCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ProcessByIT {
            get {
                return this.ProcessByITField;
            }
            set {
                if ((this.ProcessByITField.Equals(value) != true)) {
                    this.ProcessByITField = value;
                    this.RaisePropertyChanged("ProcessByIT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SyncId {
            get {
                return this.SyncIdField;
            }
            set {
                if ((this.SyncIdField.Equals(value) != true)) {
                    this.SyncIdField = value;
                    this.RaisePropertyChanged("SyncId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UoM {
            get {
                return this.UoMField;
            }
            set {
                if ((object.ReferenceEquals(this.UoMField, value) != true)) {
                    this.UoMField = value;
                    this.RaisePropertyChanged("UoM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SCSyncService.ISCSyncService")]
    public interface ISCSyncService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCSyncService/ResetData", ReplyAction="http://tempuri.org/ISCSyncService/ResetDataResponse")]
        TestWebservice.SCSyncService.ItemEntity[] ResetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCSyncService/UpdateSCDesktop", ReplyAction="http://tempuri.org/ISCSyncService/UpdateSCDesktopResponse")]
        long UpdateSCDesktop(TestWebservice.SCSyncService.ItemEntity[] dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCSyncService/GetPing", ReplyAction="http://tempuri.org/ISCSyncService/GetPingResponse")]
        string GetPing();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISCSyncServiceChannel : TestWebservice.SCSyncService.ISCSyncService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SCSyncServiceClient : System.ServiceModel.ClientBase<TestWebservice.SCSyncService.ISCSyncService>, TestWebservice.SCSyncService.ISCSyncService {
        
        public SCSyncServiceClient() {
        }
        
        public SCSyncServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SCSyncServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCSyncServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCSyncServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestWebservice.SCSyncService.ItemEntity[] ResetData() {
            return base.Channel.ResetData();
        }
        
        public long UpdateSCDesktop(TestWebservice.SCSyncService.ItemEntity[] dt) {
            return base.Channel.UpdateSCDesktop(dt);
        }
        
        public string GetPing() {
            return base.Channel.GetPing();
        }
    }
}
