//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapUtility.MiscServiceGroup {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Infolog", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Infolog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoapUtility.MiscServiceGroup.InfologEntry[] EntriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapUtility.MiscServiceGroup.InfologEntry[] Entries {
            get {
                return this.EntriesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntriesField, value) != true)) {
                    this.EntriesField = value;
                    this.RaisePropertyChanged("Entries");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologEntry", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class InfologEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoapUtility.MiscServiceGroup.InfologType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapUtility.MiscServiceGroup.InfologType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologType", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    public enum InfologType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcmcSalesLineContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class AcmcSalesLineContract : SoapUtility.MiscServiceGroup.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExclusiveHalfPalletField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InventTransIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsHalfPalletField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LineRecIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoapUtility.MiscServiceGroup.InventByGrLocContract[] LocationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PickingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalesIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalesQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalesQtyBoxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalesQtyPalletField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalesQtySQMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalesQtySQMRemainingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalesQtySQMReservedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalesUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoapUtility.MiscServiceGroup.PalletStatus UpdateStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarehouseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string wLocationIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExclusiveHalfPallet {
            get {
                return this.ExclusiveHalfPalletField;
            }
            set {
                if ((this.ExclusiveHalfPalletField.Equals(value) != true)) {
                    this.ExclusiveHalfPalletField = value;
                    this.RaisePropertyChanged("ExclusiveHalfPallet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grade {
            get {
                return this.GradeField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeField, value) != true)) {
                    this.GradeField = value;
                    this.RaisePropertyChanged("Grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InventTransID {
            get {
                return this.InventTransIDField;
            }
            set {
                if ((object.ReferenceEquals(this.InventTransIDField, value) != true)) {
                    this.InventTransIDField = value;
                    this.RaisePropertyChanged("InventTransID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHalfPallet {
            get {
                return this.IsHalfPalletField;
            }
            set {
                if ((this.IsHalfPalletField.Equals(value) != true)) {
                    this.IsHalfPalletField = value;
                    this.RaisePropertyChanged("IsHalfPallet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIdField, value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LineRecId {
            get {
                return this.LineRecIdField;
            }
            set {
                if ((this.LineRecIdField.Equals(value) != true)) {
                    this.LineRecIdField = value;
                    this.RaisePropertyChanged("LineRecId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapUtility.MiscServiceGroup.InventByGrLocContract[] Locations {
            get {
                return this.LocationsField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationsField, value) != true)) {
                    this.LocationsField = value;
                    this.RaisePropertyChanged("Locations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickingId {
            get {
                return this.PickingIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PickingIdField, value) != true)) {
                    this.PickingIdField = value;
                    this.RaisePropertyChanged("PickingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesId {
            get {
                return this.SalesIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesIdField, value) != true)) {
                    this.SalesIdField = value;
                    this.RaisePropertyChanged("SalesId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SalesQty {
            get {
                return this.SalesQtyField;
            }
            set {
                if ((this.SalesQtyField.Equals(value) != true)) {
                    this.SalesQtyField = value;
                    this.RaisePropertyChanged("SalesQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SalesQtyBox {
            get {
                return this.SalesQtyBoxField;
            }
            set {
                if ((this.SalesQtyBoxField.Equals(value) != true)) {
                    this.SalesQtyBoxField = value;
                    this.RaisePropertyChanged("SalesQtyBox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SalesQtyPallet {
            get {
                return this.SalesQtyPalletField;
            }
            set {
                if ((this.SalesQtyPalletField.Equals(value) != true)) {
                    this.SalesQtyPalletField = value;
                    this.RaisePropertyChanged("SalesQtyPallet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SalesQtySQM {
            get {
                return this.SalesQtySQMField;
            }
            set {
                if ((this.SalesQtySQMField.Equals(value) != true)) {
                    this.SalesQtySQMField = value;
                    this.RaisePropertyChanged("SalesQtySQM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SalesQtySQMRemaining {
            get {
                return this.SalesQtySQMRemainingField;
            }
            set {
                if ((this.SalesQtySQMRemainingField.Equals(value) != true)) {
                    this.SalesQtySQMRemainingField = value;
                    this.RaisePropertyChanged("SalesQtySQMRemaining");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SalesQtySQMReserved {
            get {
                return this.SalesQtySQMReservedField;
            }
            set {
                if ((this.SalesQtySQMReservedField.Equals(value) != true)) {
                    this.SalesQtySQMReservedField = value;
                    this.RaisePropertyChanged("SalesQtySQMReserved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesUnit {
            get {
                return this.SalesUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesUnitField, value) != true)) {
                    this.SalesUnitField = value;
                    this.RaisePropertyChanged("SalesUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serial {
            get {
                return this.SerialField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialField, value) != true)) {
                    this.SerialField = value;
                    this.RaisePropertyChanged("Serial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shade {
            get {
                return this.ShadeField;
            }
            set {
                if ((object.ReferenceEquals(this.ShadeField, value) != true)) {
                    this.ShadeField = value;
                    this.RaisePropertyChanged("Shade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Site {
            get {
                return this.SiteField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteField, value) != true)) {
                    this.SiteField = value;
                    this.RaisePropertyChanged("Site");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapUtility.MiscServiceGroup.PalletStatus UpdateStatus {
            get {
                return this.UpdateStatusField;
            }
            set {
                if ((this.UpdateStatusField.Equals(value) != true)) {
                    this.UpdateStatusField = value;
                    this.RaisePropertyChanged("UpdateStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Warehouse {
            get {
                return this.WarehouseField;
            }
            set {
                if ((object.ReferenceEquals(this.WarehouseField, value) != true)) {
                    this.WarehouseField = value;
                    this.RaisePropertyChanged("Warehouse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string wLocationId {
            get {
                return this.wLocationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.wLocationIdField, value) != true)) {
                    this.wLocationIdField = value;
                    this.RaisePropertyChanged("wLocationId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProxyBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.KernelInterop")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.MiscServiceGroup.XppObjectBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.MiscServiceGroup.InventByGrLocContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.MiscServiceGroup.EamWorkitemsContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.MiscServiceGroup.UnderStockItemContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.MiscServiceGroup.AcmcSalesLineContract))]
    public partial class ProxyBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.MiscServiceGroup.InventByGrLocContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.MiscServiceGroup.EamWorkitemsContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.MiscServiceGroup.UnderStockItemContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.MiscServiceGroup.AcmcSalesLineContract))]
    public partial class XppObjectBase : SoapUtility.MiscServiceGroup.ProxyBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InventByGrLocContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class InventByGrLocContract : SoapUtility.MiscServiceGroup.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OnHandField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grade {
            get {
                return this.GradeField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeField, value) != true)) {
                    this.GradeField = value;
                    this.RaisePropertyChanged("Grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationIdField, value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OnHand {
            get {
                return this.OnHandField;
            }
            set {
                if ((this.OnHandField.Equals(value) != true)) {
                    this.OnHandField = value;
                    this.RaisePropertyChanged("OnHand");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EamWorkitemsContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class EamWorkitemsContract : SoapUtility.MiscServiceGroup.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmSTO_ActualRequesterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmSTO_RefRequistNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmSTO_RequesterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmSto_CostCenterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmSto_HostRIFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int parmSto_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmSto_ItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmSto_OperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal parmSto_QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmSto_ReqNoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime parmSto_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long parmSto_WmsLocIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmSTO_ActualRequester {
            get {
                return this.parmSTO_ActualRequesterField;
            }
            set {
                if ((object.ReferenceEquals(this.parmSTO_ActualRequesterField, value) != true)) {
                    this.parmSTO_ActualRequesterField = value;
                    this.RaisePropertyChanged("parmSTO_ActualRequester");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmSTO_RefRequistNum {
            get {
                return this.parmSTO_RefRequistNumField;
            }
            set {
                if ((object.ReferenceEquals(this.parmSTO_RefRequistNumField, value) != true)) {
                    this.parmSTO_RefRequistNumField = value;
                    this.RaisePropertyChanged("parmSTO_RefRequistNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmSTO_Requester {
            get {
                return this.parmSTO_RequesterField;
            }
            set {
                if ((object.ReferenceEquals(this.parmSTO_RequesterField, value) != true)) {
                    this.parmSTO_RequesterField = value;
                    this.RaisePropertyChanged("parmSTO_Requester");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmSto_CostCenter {
            get {
                return this.parmSto_CostCenterField;
            }
            set {
                if ((object.ReferenceEquals(this.parmSto_CostCenterField, value) != true)) {
                    this.parmSto_CostCenterField = value;
                    this.RaisePropertyChanged("parmSto_CostCenter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmSto_HostRIF {
            get {
                return this.parmSto_HostRIFField;
            }
            set {
                if ((object.ReferenceEquals(this.parmSto_HostRIFField, value) != true)) {
                    this.parmSto_HostRIFField = value;
                    this.RaisePropertyChanged("parmSto_HostRIF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int parmSto_ID {
            get {
                return this.parmSto_IDField;
            }
            set {
                if ((this.parmSto_IDField.Equals(value) != true)) {
                    this.parmSto_IDField = value;
                    this.RaisePropertyChanged("parmSto_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmSto_Item {
            get {
                return this.parmSto_ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.parmSto_ItemField, value) != true)) {
                    this.parmSto_ItemField = value;
                    this.RaisePropertyChanged("parmSto_Item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmSto_Operator {
            get {
                return this.parmSto_OperatorField;
            }
            set {
                if ((object.ReferenceEquals(this.parmSto_OperatorField, value) != true)) {
                    this.parmSto_OperatorField = value;
                    this.RaisePropertyChanged("parmSto_Operator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal parmSto_Quantity {
            get {
                return this.parmSto_QuantityField;
            }
            set {
                if ((this.parmSto_QuantityField.Equals(value) != true)) {
                    this.parmSto_QuantityField = value;
                    this.RaisePropertyChanged("parmSto_Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmSto_ReqNote {
            get {
                return this.parmSto_ReqNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.parmSto_ReqNoteField, value) != true)) {
                    this.parmSto_ReqNoteField = value;
                    this.RaisePropertyChanged("parmSto_ReqNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime parmSto_Time {
            get {
                return this.parmSto_TimeField;
            }
            set {
                if ((this.parmSto_TimeField.Equals(value) != true)) {
                    this.parmSto_TimeField = value;
                    this.RaisePropertyChanged("parmSto_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long parmSto_WmsLocID {
            get {
                return this.parmSto_WmsLocIDField;
            }
            set {
                if ((this.parmSto_WmsLocIDField.Equals(value) != true)) {
                    this.parmSto_WmsLocIDField = value;
                    this.RaisePropertyChanged("parmSto_WmsLocID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnderStockItemContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class UnderStockItemContract : SoapUtility.MiscServiceGroup.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EngagedInDepositField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EngagedInPickupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ItemStockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UnderStockValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EngagedInDeposit {
            get {
                return this.EngagedInDepositField;
            }
            set {
                if ((this.EngagedInDepositField.Equals(value) != true)) {
                    this.EngagedInDepositField = value;
                    this.RaisePropertyChanged("EngagedInDeposit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EngagedInPickup {
            get {
                return this.EngagedInPickupField;
            }
            set {
                if ((this.EngagedInPickupField.Equals(value) != true)) {
                    this.EngagedInPickupField = value;
                    this.RaisePropertyChanged("EngagedInPickup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemDescription {
            get {
                return this.ItemDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemDescriptionField, value) != true)) {
                    this.ItemDescriptionField = value;
                    this.RaisePropertyChanged("ItemDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIdField, value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemNote {
            get {
                return this.ItemNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNoteField, value) != true)) {
                    this.ItemNoteField = value;
                    this.RaisePropertyChanged("ItemNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ItemStock {
            get {
                return this.ItemStockField;
            }
            set {
                if ((this.ItemStockField.Equals(value) != true)) {
                    this.ItemStockField = value;
                    this.RaisePropertyChanged("ItemStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnderStockValue {
            get {
                return this.UnderStockValueField;
            }
            set {
                if ((this.UnderStockValueField.Equals(value) != true)) {
                    this.UnderStockValueField = value;
                    this.RaisePropertyChanged("UnderStockValue");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PalletStatus", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public enum PalletStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Search = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Remove = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reserve = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnReserve = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PickingList = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Fault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="SOReserve", ConfigurationName="MiscServiceGroup.SOReserve")]
    public interface SOReserve {
        
        // CODEGEN: Generating message contract since message PalletsReserving has headers
        [System.ServiceModel.OperationContractAttribute(Action="SOReserve/SOReserve/PalletsReserving", ReplyAction="SOReserve/SOReserve/PalletsReservingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.MiscServiceGroup.Fault), Action="SOReserve/SOReserve/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapUtility.MiscServiceGroup.PalletsReservingResponse PalletsReserving(SoapUtility.MiscServiceGroup.PalletsReserving request);
        
        // CODEGEN: Generating message contract since message ServiceTest has headers
        [System.ServiceModel.OperationContractAttribute(Action="SOReserve/SOReserve/ServiceTest", ReplyAction="SOReserve/SOReserve/ServiceTestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.MiscServiceGroup.Fault), Action="SOReserve/SOReserve/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapUtility.MiscServiceGroup.ServiceTestResponse ServiceTest(SoapUtility.MiscServiceGroup.ServiceTest request);
        
        // CODEGEN: Generating message contract since message PostedWorkItemsNew has headers
        [System.ServiceModel.OperationContractAttribute(Action="SOReserve/SOReserve/PostedWorkItemsNew", ReplyAction="SOReserve/SOReserve/PostedWorkItemsNewResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.MiscServiceGroup.Fault), Action="SOReserve/SOReserve/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapUtility.MiscServiceGroup.PostedWorkItemsNewResponse PostedWorkItemsNew(SoapUtility.MiscServiceGroup.PostedWorkItemsNew request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PalletsReserving", WrapperNamespace="SOReserve", IsWrapped=true)]
    public partial class PalletsReserving {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.MiscServiceGroup.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SOReserve", Order=0)]
        public string _configId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SOReserve", Order=1)]
        public string _itemId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SOReserve", Order=2)]
        public long _lineRecId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SOReserve", Order=3)]
        public string _pickingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SOReserve", Order=4)]
        public string _salesId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SOReserve", Order=5)]
        public string device;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SOReserve", Order=6)]
        public SoapUtility.MiscServiceGroup.AcmcSalesLineContract[] pallets;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SOReserve", Order=7)]
        public string userName;
        
        public PalletsReserving() {
        }
        
        public PalletsReserving(SoapUtility.MiscServiceGroup.CallContext CallContext, string _configId, string _itemId, long _lineRecId, string _pickingId, string _salesId, string device, SoapUtility.MiscServiceGroup.AcmcSalesLineContract[] pallets, string userName) {
            this.CallContext = CallContext;
            this._configId = _configId;
            this._itemId = _itemId;
            this._lineRecId = _lineRecId;
            this._pickingId = _pickingId;
            this._salesId = _salesId;
            this.device = device;
            this.pallets = pallets;
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PalletsReservingResponse", WrapperNamespace="SOReserve", IsWrapped=true)]
    public partial class PalletsReservingResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.MiscServiceGroup.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SOReserve", Order=0)]
        public SoapUtility.MiscServiceGroup.AcmcSalesLineContract[] result;
        
        public PalletsReservingResponse() {
        }
        
        public PalletsReservingResponse(SoapUtility.MiscServiceGroup.Infolog Infolog, SoapUtility.MiscServiceGroup.AcmcSalesLineContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServiceTest", WrapperNamespace="SOReserve", IsWrapped=true)]
    public partial class ServiceTest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.MiscServiceGroup.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SOReserve", Order=0)]
        public string _name;
        
        public ServiceTest() {
        }
        
        public ServiceTest(SoapUtility.MiscServiceGroup.CallContext CallContext, string _name) {
            this.CallContext = CallContext;
            this._name = _name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServiceTestResponse", WrapperNamespace="SOReserve", IsWrapped=true)]
    public partial class ServiceTestResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.MiscServiceGroup.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SOReserve", Order=0)]
        public string result;
        
        public ServiceTestResponse() {
        }
        
        public ServiceTestResponse(SoapUtility.MiscServiceGroup.Infolog Infolog, string result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostedWorkItemsNew", WrapperNamespace="SOReserve", IsWrapped=true)]
    public partial class PostedWorkItemsNew {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.MiscServiceGroup.CallContext CallContext;
        
        public PostedWorkItemsNew() {
        }
        
        public PostedWorkItemsNew(SoapUtility.MiscServiceGroup.CallContext CallContext) {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostedWorkItemsNewResponse", WrapperNamespace="SOReserve", IsWrapped=true)]
    public partial class PostedWorkItemsNewResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.MiscServiceGroup.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SOReserve", Order=0)]
        public SoapUtility.MiscServiceGroup.EamWorkitemsContract[] result;
        
        public PostedWorkItemsNewResponse() {
        }
        
        public PostedWorkItemsNewResponse(SoapUtility.MiscServiceGroup.Infolog Infolog, SoapUtility.MiscServiceGroup.EamWorkitemsContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SOReserveChannel : SoapUtility.MiscServiceGroup.SOReserve, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SOReserveClient : System.ServiceModel.ClientBase<SoapUtility.MiscServiceGroup.SOReserve>, SoapUtility.MiscServiceGroup.SOReserve {
        
        public SOReserveClient() {
        }
        
        public SOReserveClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SOReserveClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOReserveClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOReserveClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapUtility.MiscServiceGroup.PalletsReservingResponse SoapUtility.MiscServiceGroup.SOReserve.PalletsReserving(SoapUtility.MiscServiceGroup.PalletsReserving request) {
            return base.Channel.PalletsReserving(request);
        }
        
        public SoapUtility.MiscServiceGroup.Infolog PalletsReserving(SoapUtility.MiscServiceGroup.CallContext CallContext, string _configId, string _itemId, long _lineRecId, string _pickingId, string _salesId, string device, SoapUtility.MiscServiceGroup.AcmcSalesLineContract[] pallets, string userName, out SoapUtility.MiscServiceGroup.AcmcSalesLineContract[] result) {
            SoapUtility.MiscServiceGroup.PalletsReserving inValue = new SoapUtility.MiscServiceGroup.PalletsReserving();
            inValue.CallContext = CallContext;
            inValue._configId = _configId;
            inValue._itemId = _itemId;
            inValue._lineRecId = _lineRecId;
            inValue._pickingId = _pickingId;
            inValue._salesId = _salesId;
            inValue.device = device;
            inValue.pallets = pallets;
            inValue.userName = userName;
            SoapUtility.MiscServiceGroup.PalletsReservingResponse retVal = ((SoapUtility.MiscServiceGroup.SOReserve)(this)).PalletsReserving(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapUtility.MiscServiceGroup.ServiceTestResponse SoapUtility.MiscServiceGroup.SOReserve.ServiceTest(SoapUtility.MiscServiceGroup.ServiceTest request) {
            return base.Channel.ServiceTest(request);
        }
        
        public SoapUtility.MiscServiceGroup.Infolog ServiceTest(SoapUtility.MiscServiceGroup.CallContext CallContext, string _name, out string result) {
            SoapUtility.MiscServiceGroup.ServiceTest inValue = new SoapUtility.MiscServiceGroup.ServiceTest();
            inValue.CallContext = CallContext;
            inValue._name = _name;
            SoapUtility.MiscServiceGroup.ServiceTestResponse retVal = ((SoapUtility.MiscServiceGroup.SOReserve)(this)).ServiceTest(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapUtility.MiscServiceGroup.PostedWorkItemsNewResponse SoapUtility.MiscServiceGroup.SOReserve.PostedWorkItemsNew(SoapUtility.MiscServiceGroup.PostedWorkItemsNew request) {
            return base.Channel.PostedWorkItemsNew(request);
        }
        
        public SoapUtility.MiscServiceGroup.Infolog PostedWorkItemsNew(SoapUtility.MiscServiceGroup.CallContext CallContext, out SoapUtility.MiscServiceGroup.EamWorkitemsContract[] result) {
            SoapUtility.MiscServiceGroup.PostedWorkItemsNew inValue = new SoapUtility.MiscServiceGroup.PostedWorkItemsNew();
            inValue.CallContext = CallContext;
            SoapUtility.MiscServiceGroup.PostedWorkItemsNewResponse retVal = ((SoapUtility.MiscServiceGroup.SOReserve)(this)).PostedWorkItemsNew(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="UnderstockItemsInfoNewService", ConfigurationName="MiscServiceGroup.UnderstockItemsInfoNewService")]
    public interface UnderstockItemsInfoNewService {
        
        // CODEGEN: Generating message contract since message CreateItems has headers
        [System.ServiceModel.OperationContractAttribute(Action="UnderstockItemsInfoNewService/UnderstockItemsInfoNewService/CreateItems", ReplyAction="UnderstockItemsInfoNewService/UnderstockItemsInfoNewService/CreateItemsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.MiscServiceGroup.Fault), Action="UnderstockItemsInfoNewService/UnderstockItemsInfoNewService/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapUtility.MiscServiceGroup.CreateItemsResponse CreateItems(SoapUtility.MiscServiceGroup.CreateItems request);
        
        // CODEGEN: Generating message contract since message deleteOld has headers
        [System.ServiceModel.OperationContractAttribute(Action="UnderstockItemsInfoNewService/UnderstockItemsInfoNewService/deleteOld", ReplyAction="UnderstockItemsInfoNewService/UnderstockItemsInfoNewService/deleteOldResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.MiscServiceGroup.Fault), Action="UnderstockItemsInfoNewService/UnderstockItemsInfoNewService/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapUtility.MiscServiceGroup.deleteOldResponse deleteOld(SoapUtility.MiscServiceGroup.deleteOld request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateItems", WrapperNamespace="UnderstockItemsInfoNewService", IsWrapped=true)]
    public partial class CreateItems {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.MiscServiceGroup.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="UnderstockItemsInfoNewService", Order=0)]
        public SoapUtility.MiscServiceGroup.UnderStockItemContract[] lines;
        
        public CreateItems() {
        }
        
        public CreateItems(SoapUtility.MiscServiceGroup.CallContext CallContext, SoapUtility.MiscServiceGroup.UnderStockItemContract[] lines) {
            this.CallContext = CallContext;
            this.lines = lines;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateItemsResponse", WrapperNamespace="UnderstockItemsInfoNewService", IsWrapped=true)]
    public partial class CreateItemsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.MiscServiceGroup.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="UnderstockItemsInfoNewService", Order=0)]
        public long result;
        
        public CreateItemsResponse() {
        }
        
        public CreateItemsResponse(SoapUtility.MiscServiceGroup.Infolog Infolog, long result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteOld", WrapperNamespace="UnderstockItemsInfoNewService", IsWrapped=true)]
    public partial class deleteOld {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.MiscServiceGroup.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="UnderstockItemsInfoNewService", Order=0)]
        public long recId;
        
        public deleteOld() {
        }
        
        public deleteOld(SoapUtility.MiscServiceGroup.CallContext CallContext, long recId) {
            this.CallContext = CallContext;
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteOldResponse", WrapperNamespace="UnderstockItemsInfoNewService", IsWrapped=true)]
    public partial class deleteOldResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.MiscServiceGroup.Infolog Infolog;
        
        public deleteOldResponse() {
        }
        
        public deleteOldResponse(SoapUtility.MiscServiceGroup.Infolog Infolog) {
            this.Infolog = Infolog;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UnderstockItemsInfoNewServiceChannel : SoapUtility.MiscServiceGroup.UnderstockItemsInfoNewService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnderstockItemsInfoNewServiceClient : System.ServiceModel.ClientBase<SoapUtility.MiscServiceGroup.UnderstockItemsInfoNewService>, SoapUtility.MiscServiceGroup.UnderstockItemsInfoNewService {
        
        public UnderstockItemsInfoNewServiceClient() {
        }
        
        public UnderstockItemsInfoNewServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UnderstockItemsInfoNewServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnderstockItemsInfoNewServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnderstockItemsInfoNewServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapUtility.MiscServiceGroup.CreateItemsResponse SoapUtility.MiscServiceGroup.UnderstockItemsInfoNewService.CreateItems(SoapUtility.MiscServiceGroup.CreateItems request) {
            return base.Channel.CreateItems(request);
        }
        
        public SoapUtility.MiscServiceGroup.Infolog CreateItems(SoapUtility.MiscServiceGroup.CallContext CallContext, SoapUtility.MiscServiceGroup.UnderStockItemContract[] lines, out long result) {
            SoapUtility.MiscServiceGroup.CreateItems inValue = new SoapUtility.MiscServiceGroup.CreateItems();
            inValue.CallContext = CallContext;
            inValue.lines = lines;
            SoapUtility.MiscServiceGroup.CreateItemsResponse retVal = ((SoapUtility.MiscServiceGroup.UnderstockItemsInfoNewService)(this)).CreateItems(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapUtility.MiscServiceGroup.deleteOldResponse SoapUtility.MiscServiceGroup.UnderstockItemsInfoNewService.deleteOld(SoapUtility.MiscServiceGroup.deleteOld request) {
            return base.Channel.deleteOld(request);
        }
        
        public SoapUtility.MiscServiceGroup.Infolog deleteOld(SoapUtility.MiscServiceGroup.CallContext CallContext, long recId) {
            SoapUtility.MiscServiceGroup.deleteOld inValue = new SoapUtility.MiscServiceGroup.deleteOld();
            inValue.CallContext = CallContext;
            inValue.recId = recId;
            SoapUtility.MiscServiceGroup.deleteOldResponse retVal = ((SoapUtility.MiscServiceGroup.UnderstockItemsInfoNewService)(this)).deleteOld(inValue);
            return retVal.Infolog;
        }
    }
}
