//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebservice.DeviceOps {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeviceOps.IDeviceOps")]
    public interface IDeviceOps {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceOps/Ping", ReplyAction="http://tempuri.org/IDeviceOps/PingResponse")]
        bool Ping(SyncServices.DeviceMessage msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceOps/SaveMessage", ReplyAction="http://tempuri.org/IDeviceOps/SaveMessageResponse")]
        bool SaveMessage(SyncServices.DeviceMessage msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceOps/SaveMessages", ReplyAction="http://tempuri.org/IDeviceOps/SaveMessagesResponse")]
        SyncServices.DeviceMessage[] SaveMessages(SyncServices.DeviceMessage[] msgs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeviceOpsChannel : TestWebservice.DeviceOps.IDeviceOps, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeviceOpsClient : System.ServiceModel.ClientBase<TestWebservice.DeviceOps.IDeviceOps>, TestWebservice.DeviceOps.IDeviceOps {
        
        public DeviceOpsClient() {
        }
        
        public DeviceOpsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeviceOpsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceOpsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceOpsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Ping(SyncServices.DeviceMessage msg) {
            return base.Channel.Ping(msg);
        }
        
        public bool SaveMessage(SyncServices.DeviceMessage msg) {
            return base.Channel.SaveMessage(msg);
        }
        
        public SyncServices.DeviceMessage[] SaveMessages(SyncServices.DeviceMessage[] msgs) {
            return base.Channel.SaveMessages(msgs);
        }
    }
}
